import math
a=math.sqrt(100)
print('square root: ',a)
b=math.pow(2,4)
print('power: ',b)
c=math.factorial(5)
print('factorial: ',c)
d=math.gcd(20,10,50)
print('gcd: ',d)
e=math.log(10,2)
print('Logarithm: ',e)
f=math.log2(10)
print("log2: ",f)
g=math.pi
print("Pi= ",g)
h=math.tau
print("Tau= ",h)
i=math.radians(90)
print("90 in radians: ",i)
j=math.degrees(90)
print("90 in degrees: ",j)
k=math.dist([5],[6])
print('distance between coordinates: ',k)
l=math.hypot(3,4)
print("Hyppotenuse of sides: ",l)